name: my_paypal_app
description: PayPal Transaction Dashboard - Course Project

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.0
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  flutter_svg: ^2.0.7
  
  # Navigation
  go_router: ^12.0.0
  
  # Data Handling
  shared_preferences: ^2.2.0
  collection: ^1.17.0
  
  # Platform Integration
  url_launcher: ^6.1.0
  package_info_plus: ^4.1.0
  
  # Development
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  # Assets will be added as needed throughout the week
  assets:
    - assets/images/
    
  # Fonts can be added if needed for custom styling
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
